<a href="https://colab.research.google.com/github/georgepappas25183/aralaral/blob/master/Copy_of_Aral_Aral_Python_Review_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h3 id="exercise">Exercise: Your First Program</h3>
<p>Generations of programmers have started their coding careers by simply printing "Hello, world!". You will be following in their footsteps.</p>
<p>In the code cell below, use the <code>print()</code> function to print out the phrase: <code>Hello, world!</code></p>

In [0]:
# Write your code below and press Shift+Enter to execute 
print("Hello World")

Hello World


<p>Now, let's enhance your code with a comment. In the code cell below, print out the phrase: <code>Hello, world!</code> and comment it with the phrase <code>Print the traditional hello world</code> all in one line of code.</p>

In [0]:
# Write your code below and press Shift+Enter to execute 
# Print the traditional hello world


<h3 id="exer_type">Exercise: Types</h3>
<p>In the code cell below, use the <code>type()</code> function to check the object type of <code>12.0</code>.

In [0]:
# Write your code below. Don't forget to press Shift+Enter to execute the cell
# float
type(12.0)

float

<p>What is the data type of the result of: <code>6 / 2</code>?</p>

In [0]:
# Write your code below. Don't forget to press Shift+Enter to execute the cell
# float
type(6/2)

float

<p>What is the type of the result of: <code>6 // 2</code>? (Note the double slash <code>//</code>.)</p>

In [0]:
# Write your code below. Don't forget to press Shift+Enter to execute the cell
# int, as the double slashes stand for integer division 
type(6//2)

int

<h3 id="exer_exp">Exercise: Expression</h3>
<p>Let's write an expression that calculates how many hours there are in 160 minutes:

In [0]:
# Write your code below. Don't forget to press Shift+Enter to execute the cell
# Or
print(160//60)


2


<h3 id="exer_exp_var">Exercise: Expression and Variables in Python</h3>
<p>What is the value of <code>x</code> where <code>x = 3 + 2 * 2</code></p>

In [0]:
# Write your code below. Don't forget to press Shift+Enter to execute the cell
x =3+2*2
print(x)

7


<p>What is the value of <code>y</code> where <code>y = (3 + 2) * 2</code>?</p>

In [0]:
# Write your code below. Don't forget to press Shift+Enter to execute the cell
y=(3+2)*2
print(y)

10


<p>What is the value of <code>z</code> where <code>z = x + y</code>?</p>

In [0]:
# Write your code below. Don't forget to press Shift+Enter to execute the cell
z=x+y
print(z)

17


<h2 id="quiz">Quiz on Tuples</h2>

Consider the following tuple:

In [0]:
# sample tuple

genres_tuple = ("pop", "rock", "soul", "hard rock", "soft rock", \
                "R&B", "progressive rock", "disco") 
genres_tuple

('pop',
 'rock',
 'soul',
 'hard rock',
 'soft rock',
 'R&B',
 'progressive rock',
 'disco')

Find the length of the tuple, <code>genres_tuple</code>:

In [0]:
# Write your code below and press Shift+Enter to execute
len(genres_tuple)

8

Access the element, with respect to index 3: 

In [0]:
# Write your code below and press Shift+Enter to execute
genres_tuple[3]

'hard rock'

Use slicing to obtain indexes 3, 4 and 5:

In [0]:
# Write your code below and press Shift+Enter to execute
genres_tuple[3:6]

('hard rock', 'soft rock', 'R&B')

Find the first two elements of the tuple <code>genres_tuple</code>:

In [0]:
# Write your code below and press Shift+Enter to execute
genres_tuple[:2]

('pop', 'rock')

Find the index of <code>"disco"</code>:

In [0]:
# Write your code below and press Shift+Enter to execute
genres_tuple.index("disco")

7

Generate a sorted List from the Tuple <code>C_tuple=(-5, 1, -3)</code>:

In [0]:
# Write your code below and press Shift+Enter to execute
C_tuple = (-5,1,-3)
sorted(C_tuple)

[-5, -3, 1]

<h2 id="quiz">Quiz on List</h2>

Create a list <code>a_list</code>, with the following elements <code>1</code>, <code>hello</code>, <code>[1,2,3]</code> and <code>True</code>. 

In [0]:
# Write your code below and press Shift+Enter to execute
a_list = [1, "hello", [1,2,3], True]
a_list

[1, 'hello', [1, 2, 3], True]

Find the value stored at index 1 of <code>a_list</code>.

In [0]:
# Write your code below and press Shift+Enter to execute
a_list[1]

'hello'

Retrieve the elements stored at index 1, 2 and 3 of <code>a_list</code>.

In [0]:
# Write your code below and press Shift+Enter to execute
a_list[1:4]

['hello', [1, 2, 3], True]

Concatenate the following lists <code>A = [1, 'a']</code> and <code>B = [2, 1, 'd']</code>:

In [0]:
# Write your code below and press Shift+Enter to execute
A = [1,'a']
B =[2,1,'d']
A+B

[1, 'a', 2, 1, 'd']

<h2 id="quiz">Quiz on Sets</h2>

Convert the list <code>['rap','house','electronic music', 'rap']</code> to a set:

In [0]:
# Write your code below and press Shift+Enter to execute
genres=['rap','house','electronic music','rap']
set(genres)

{'electronic music', 'house', 'rap'}

Consider the list <code>A = [1, 2, 2, 1]</code> and set <code>B = set([1, 2, 2, 1])</code>, does <code>sum(A) = sum(B)</code> 

In [0]:
# Write your code below and press Shift+Enter to execute
A=[1,2,2,1]
B=set([1,2,2,1])
sum(A)-sum(B)

3

Create a new set <code>album_set3</code> that is the union of <code>album_set1</code> and <code>album_set2</code>:

In [0]:
# Write your code below and press Shift+Enter to execute

Find out if <code>album_set1</code> is a subset of <code>album_set3</code>:

In [0]:
# Write your code below and press Shift+Enter to execute

<h2 id="quiz">Quiz on Dictionaries</h2>

<b>You will need this dictionary for the next two questions:</b>

In [0]:
# Question sample dictionary
soundtrack_dict

NameError: ignored

a) In the dictionary <code>soundtrack_dict</code> what are the keys ?

In [0]:
# Write your code below and press Shift+Enter to execute
# The Keys "The Bodyguard" and "Saturday Night Fever" 

b) In the dictionary <code>soundtrack_dict</code> what are the values ?

In [0]:
# Write your code below and press Shift+Enter to execute
# The values are "1992" and "1977"

<b>You will need this dictionary for the following questions:</b>

The Albums <b>Back in Black</b>, <b>The Bodyguard</b> and <b>Thriller</b> have the following music recording sales in millions 50, 50 and 65 respectively:

a) Create a dictionary <code>album_sales_dict</code> where the keys are the album name and the sales in millions are the values. 

In [0]:
# Write your code below and press Shift+Enter to execute
album_sales_dict={"Back in Black":50, 'The Bodyguard':50,'Thriller':65}
album_sales_dict

{'Back in Black': 50, 'The Bodyguard': 50, 'Thriller': 65}

b) Use the dictionary to find the total sales of <b>Thriller</b>:

In [0]:
# Write your code below and press Shift+Enter to execute
album_sales_dict["Thriller"]

65

c) Find the names of the albums from the dictionary using the method <code>keys</code>:

In [0]:
# Write your code below and press Shift+Enter to execute
album_sales_dict.keys()

dict_keys(['Back in Black', 'The Bodyguard', 'Thriller'])

d) Find the names of the recording sales from the dictionary using the method <code>values</code>:

In [0]:
# Write your code below and press Shift+Enter to execute
album_sales_dict.values()

dict_values([50, 50, 65])

<h2 id="quiz">Quiz on Conditions</h2>

Write an if statement to determine if an album had a rating greater than 8. Test it using the rating for the album <b>“Back in Black”</b> that had a rating of 8.5. If the statement is true print "This album is Amazing!"

In [0]:
# Write your code below and press Shift+Enter to execute
album_rating_dict={"Back in Black":8.5}

if album_rating_dict["Back in Black"] > 8:
  print("This album is Amazing")

This album is Amazing


Write an if-else statement that performs the following. If the rating is larger then eight print “this album is amazing”. If the rating is less than or equal to 8 print “this album is ok”.

In [0]:
# Write your code below and press Shift+Enter to execute

if album_rating_dict["Back in Black"] > 8:
  print("This album is Amazing")
else:
  print("This album is ok")

This album is Amazing


Write an if statement to determine if an album came out before 1980 or in the years: 1991 or 1993. If the condition is true print out the year the album came out.

In [0]:
# Write your code below and press Shift+Enter to execute
a = 1995

if a < 1980:
    print(a)
elif a == 1991:
    print(a)
elif a == 1993:
    print(a) 
else:
  print("deins")


deins


<h2 id="quiz">Quiz on Loops</h2>

Write a <code>for</code> loop the prints out all the element between <b>-5</b> and <b>5</b> using the range function.

In [0]:
# Write your code below and press Shift+Enter to execute
 range(-5,5)
 for x in range(-5,5):
  print(x)

-5
-4
-3
-2
-1
0
1
2
3
4


Print the elements of the following list:
<code>Genres=[ 'rock', 'R&B', 'Soundtrack', 'R&B', 'soul', 'pop']</code>
Make sure you follow Python conventions.

In [0]:
# Write your code below and press Shift+Enter to execute
Genres=[ 'rock', 'R&B', 'Soundtrack', 'R&B', 'soul', 'pop']
for x in Genres:
  print(x)

rock
R&B
Soundtrack
R&B
soul
pop


Write a for loop that prints out the following list: <code>squares=['red', 'yellow', 'green', 'purple', 'blue']</code>

In [0]:
# Write your code below and press Shift+Enter to execute
squares=['red', 'yellow', 'green', 'purple', 'blue']
for x in squares: 
  print(x)

red
yellow
green
purple
blue


Write a while loop to display the values of the Rating of an album playlist stored in the list <code>PlayListRatings</code>. If the score is less than 6, exit the loop. The list <code>PlayListRatings</code> is given by: <code>PlayListRatings = [10, 9.5, 10, 8, 7.5, 5, 10, 10]</code>

In [0]:
# Write your code below and press Shift+Enter to execute
PlayListRatings = [10, 9.5, 10, 8, 7.5, 5, 10, 10]
i=0
rating=PlayListRatings[i]
while i < len(PlayListRatings):
  rating=PlayListRatings[i]
  i+=1
  if rating < 6:
    break
    
  print(rating)
    

10
9.5
10
8
7.5


Write a while loop to copy the strings <code>'orange'</code> of the list <code>squares</code> to the list <code>new_squares</code>. Stop and exit the loop if the value on the list is not <code>'orange'</code>:

In [0]:
# Write your code below and press Shift+Enter to execute
squares = ["orange","orange","orange","peanuts"]
new_squares = []
i=0
string=squares[i]
while i < len(squares):
  i+=1
  if string != "orange":
    break
      
    new_squares.insert(string)
    
    new_squares


In [0]:
new_squares

[]

<h2>Quiz on Functions</h2>

Come up with a function that divides the first input by the second input:

In [0]:
# Write your code below and press Shift+Enter to execute
def function(a,b):
  print(a/b)
  
function(2,1)

2.0


Use the function <code>con</code> for the following question.

In [0]:
# Use the con function for the following question

Can the <code>con</code> function we defined before be used to add to integers or strings?

In [0]:
# Write your code below and press Shift+Enter to execute

Can the <code>con</code> function we defined before be used to concentrate a list or tuple?

In [0]:
# Write your code below and press Shift+Enter to execute

<h2 id="quiz">Quiz on 1D Numpy Array</h2>

Implement the following vector subtraction in numpy: u-v

In [0]:
# Write your code below and press Shift+Enter to execute
import numpy
u=numpy.array([1,2,3,4])
v=numpy.array([3,4,5,6])

u-v

array([-2, -2, -2, -2])

Multiply the numpy array z with -2:

In [0]:
# Write your code below and press Shift+Enter to execute
z=numpy.array([5,6,7,8])
z*2

array([10, 12, 14, 16])

Consider the list <code>[1, 2, 3, 4, 5]</code> and <code>[1, 0, 1, 0, 1]</code>, and cast both lists to a numpy array then multiply them together:

In [0]:
# Write your code below and press Shift+Enter to execute
r=numpy.array([1, 2, 3, 4, 5])
q=numpy.array([1, 0, 1, 0, 1])

r*q

array([1, 0, 3, 0, 5])

Convert the list <code>[-1, 1]</code> and <code>[1, 1]</code> to numpy arrays <code>a</code> and <code>b</code>.  Then, plot the arrays as vectors using the fuction <code>Plotvec2</code> and find the dot product:

In [0]:
# Write your code below and press Shift+Enter to execute
a=numpy.array([-1,1])
b=numpy.array([1,1])

import matplotlib.pyplot

def Plotvec2(a,b):
  ax = plt.axes()
  
numpy.dot(a,b)

0

Convert the list <code>[1, 0]</code> and <code>[0, 1]</code> to numpy arrays <code>a</code> and <code>b</code>. Then, plot the arrays as vectors using the function <code>Plotvec2</code> and find the dot product:

In [0]:
# Write your code below and press Shift+Enter to execute

Convert the list <code>[1, 1]</code> and <code>[0, 1]</code> to numpy arrays <code>a</code> and <code>b</code>. Then plot the arrays as vectors using the fuction <code>Plotvec2</code> and find the dot product:

In [0]:
# Write your code below and press Shift+Enter to execute

Why are the results of the dot product for <code>[-1, 1]</code> and <code>[1, 1]</code> and the dot product for <code>[1, 0]</code> and <code>[0, 1]</code> zero, but not zero for the dot product for <code>[1, 1]</code> and <code>[0, 1]</code>? <p><i>Hint: Study the corresponding figures, pay attention to the direction the arrows are pointing to.</i></p>

In [0]:
# Write your code below and press Shift+Enter to execute
#The vectors used for question 4 and 5 are perpendicular. As a result, the dot product is zero. 